/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.financialmanui;

import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

import RMI.client.RMIClient;
import blservice.financialmanblservice.CostManageService;
import vo.financialmanvo.RecieveListvo;

/**
 *
 * @author user
 */
public class CheckGathering extends javax.swing.JFrame {
	static CostManageService cm;
    /**
     * Creates new form CheckGathering
     * @throws Exception 
     */
    public CheckGathering() throws Exception {
        initComponents();
        receive.setVisible(false);
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setVisible(true);
        RMIClient.init();
        cm = RMIClient.getCostManageService();
//        System.out.println("sssss");
    }
//    static final String s[] = new String [100];
    static final String ss[] = new String [100];//计算合计收款单
    static final String sp[] = new String [100];//计算合计付款单
    static  int count=0;
    static  int chu=0;
//    static final RecieveListvo[] v=new String [100];
    private void SearchAll(RecieveListvo[] uv){
    	
    	int j=0;
//  	   final String s[] = new String [100];
  	   if(uv!=null){	
  		final String s[] = new String [100];
  	   for(int i=0;i<uv.length;i++){
  		   s[i]=uv[i].yearq+"-"+uv[i].monthq+"-"+uv[i].dayq+"                     "+uv[i].moneyq+"                         "
  				   +uv[i].tiaoxingmaq+"                 "+uv[i].kuaidiyuanq+"    "+uv[i].Zhanghu;
  		   ss[i]=uv[i].moneyq;
  		   j++;
  	   }
  	   count=j;
  	 jList1.setModel(new javax.swing.AbstractListModel() {
         String[] strings = s;
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
     });
	   jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
	    jScrollPane1.setViewportView(jList1);
 }}
    
    
    
    
    
//    private void SearchAll2(PaymentInputvo[] pv){
////    	int z=0;
//    	   final String s1[] = new String [100];
//    	   if(pv!=null){	   
//    	   for(int i=0;i<pv.length;i++){
//    		   s1[i]=pv[i].date.year+"-"+pv[i].date.mouth+"-"+pv[i].date.day+"                 "+pv[i].pay.money+"元"+"                    "
//    				   +pv[i].pay.account;
//    		   sp[i]=pv[i].pay.money;
//    		   chu++;
//    	   }
//    	  
//    	    }}
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        month = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        day = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yytID = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        heji = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        receive = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("日期：");

        jLabel2.setText("年");

        jLabel3.setText("月");

        day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayActionPerformed(evt);
            }
        });

        jLabel4.setText("日");

        jLabel5.setText("营业厅编号：");

        OK.setText("确定");
        OK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					OKMouseClicked(evt);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButton2.setText("退出");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " ", " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("此营业厅该日期所有收款单信息");

        jLabel7.setText("收款日期");

        jLabel8.setText("收款金额");

        jLabel9.setText("收款快递员");

        jLabel10.setText("订单条形码号");

        jLabel11.setText("收款账户");

        heji.setText("合计");
        heji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					hejiMouseClicked(evt);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        receive.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel10)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(heji)
                        .addGap(93, 93, 93)
                        .addComponent(jButton2)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel11)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))
                                    .addComponent(yytID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(5, 5, 5)))
                        .addComponent(OK))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(receive)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yytID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(receive)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(heji)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dayActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void OKMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException{//GEN-FIRST:event_OKMouseClicked
        // TODO add your handling code here:
    	String y=year.getText();
    	String m=month.getText();
    	String d=day.getText();
    	String yy=yytID.getText();
    	Date date=new Date();
		DateFormat format=new SimpleDateFormat("yyyy");
		String time1=format.format(date);
		
		Date date2=new Date();
		DateFormat format2=new SimpleDateFormat("MM");
		String time2=format2.format(date2);
		
		Date date3=new Date();
		DateFormat format3=new SimpleDateFormat("dd");
		String time3=format3.format(date3);
		
		//完整性
    	if(y.equals("")||m.equals("")||d.equals("")||yy.equals("")){
    		missMes();
    		return;
    	}
    	
    	
    	
    	//检测是否有非法字符
    	for(int i=0;i<y.length();i++){
    		if('0'>y.charAt(i)||y.charAt(i)>'9'){
    			Wrong();
    		    return;
    		}
    	}
    	for(int i=0;i<m.length();i++){
    		if('0'>m.charAt(i)||m.charAt(i)>'9'){
    			Wrong();
    		    return;
    		}
    	}
    	for(int i=0;i<d.length();i++){
    		if('0'>d.charAt(i)||d.charAt(i)>'9'){
    			Wrong();
    		    return;
    		}
    	}
    	for(int i=0;i<yy.length();i++){
    		if('0'>yy.charAt(i)||yy.charAt(i)>'9'){
    			Wrong();
    		    return;
    		}
    	}
    	
    	
    	if(Integer.parseInt(time1)<Integer.parseInt(y)||Integer.parseInt(time2)<Integer.parseInt(m)
    			||Integer.parseInt(time3)<Integer.parseInt(d)){
    		WrongTime();
    		return;
    	}
    	
    	
    	
    	if(yy.length()!=6){
    		JOptionPane.showMessageDialog(null, "营业厅编号为6位", "输入有误", JOptionPane.ERROR_MESSAGE);
    		return;
    	}
    		
    	
    	SearchAll(cm.SearchByMes(year.getText(),month.getText(),day.getText(),yytID.getText()));
//    	chu++;
//    	System.out.println(count+"上");
  	  
	    
    }//GEN-LAST:event_OKMouseClicked
    private void Wrong(){
    	 JOptionPane.showMessageDialog(null, "非法字符", "输入有误", JOptionPane.ERROR_MESSAGE);
    }
    private void WrongTime(){
    	 JOptionPane.showMessageDialog(null, "请输入正确时间","输入有误",  JOptionPane.ERROR_MESSAGE);
    }
    private void missMes(){
      	 JOptionPane.showMessageDialog(null, "信息输入不完整","输入有误", JOptionPane.ERROR_MESSAGE);
      }
   

    private void hejiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hejiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hejiActionPerformed

    private void hejiMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_hejiMouseClicked
        // TODO add your handling code here:

    	//算合计的时候在UI层直接算还是到logic里面算好再传回来！！！！！！！！！！！！！！！！！！！！！！！
//    	int sum=0;
//    	int q=count;
//    	
//    	for(int i=0;i<q;i++){
//    		sum+=Integer.parseInt(ss[i]);
//    	}
    	int sum=cm.getSum(ss,count);
    	

    	receive.setText("合计金额：  "+sum+" 元");
    	receive.setVisible(true);
    }//GEN-LAST:event_hejiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckGathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckGathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckGathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckGathering.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new CheckGathering().setVisible(true);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JTextField day;
    private javax.swing.JButton heji;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JLabel receive;
    private javax.swing.JTextField year;
    private javax.swing.JTextField yytID;
    // End of variables declaration//GEN-END:variables
}
