/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.financialmanui;

import java.rmi.RemoteException;

import javax.swing.JOptionPane;

import RMI.client.RMIClient;
import blservice.financialmanblservice.AccountManageService;
import presentation.bushallsalmanui.CarMesManageui;
import presentation.generalmanagerui.Institutionadd;
import presentation.generalmanagerui.Staffadd;
import presentation.stockmanagermanui.WarehouseWarningui;

/**
 *
 * @author user
 */
public class Init extends javax.swing.JFrame {
	static AccountManageService as;

    /**
     * Creates new form Init
     * @throws Exception 
     */
    public Init() throws Exception {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setVisible(true);
        RMIClient.init();
        as= RMIClient.getAccountManageService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jigou = new javax.swing.JButton();
        renyuan = new javax.swing.JButton();
        cheliang = new javax.swing.JButton();
        kucun = new javax.swing.JButton();
        accout = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jigou.setText("期初机构设置");
        jigou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jigouMouseClicked(evt);
            }
        });

        renyuan.setText("期初人员设置");
        renyuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renyuanMouseClicked(evt);
            }
        });

        cheliang.setText("期初车辆设置");
        cheliang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheliangMouseClicked(evt);
            }
        });

        kucun.setText("期初库存设置");
        kucun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kucunMouseClicked(evt);
            }
        });

        accout.setText("期初银行账户设置");
        accout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accoutMouseClicked(evt);
            }
        });

        jButton6.setText("返回");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
					jButton6MouseClicked(evt);
				} catch (RemoteException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kucun)
                            .addComponent(renyuan)
                            .addComponent(jigou)
                            .addComponent(cheliang)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(accout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jButton6)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jigou)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renyuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cheliang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kucun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
         
         //以下为点了返回之后，把期初信息单独存储起来
         //机构
    	if(!as.writeInitJigou()){
    		missJigou();
    		return;//未写完机构，只到bl层
    	}
//         人员
    	if(!as.writeInitRenyuan()){
    		missRenyuan();
    		return;//未写完机构，只到bl层
    	}
//         库存
    	if(!as.writeInitKucun()){
    		missKucun();
    		return;//未写完机构，只到bl层
    	}
//         银行账户
        if(!as.writeInitAccount()){
        	missAccount();
        	return;
        	
        }
        	
//         车辆
        if(!as.writeInitCheliang()){
        	missCheliang();
        	return;
        }
    	
    	
    	
    	this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jigouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jigouMouseClicked
        // TODO add your handling code here:
    	try {
			new Institutionadd().setVisible(true);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    }//GEN-LAST:event_jigouMouseClicked

    private void renyuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renyuanMouseClicked
        // TODO add your handling code here:
    	try {
			new Staffadd().setVisible(true);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_renyuanMouseClicked

    private void cheliangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheliangMouseClicked
        // TODO add your handling code here:
    	try {
			new CarMesManageui().setVisible(true);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_cheliangMouseClicked

    private void kucunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kucunMouseClicked
        // TODO add your handling code here:
    	try {
			new WarehouseWarningui().setVisible(true);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_kucunMouseClicked

    private void accoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accoutMouseClicked
        // TODO add your handling code here:
    	try {
			new AddAccount().setVisible(true);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }//GEN-LAST:event_accoutMouseClicked
    private void missAccount(){
     	 JOptionPane.showMessageDialog(null, "未设置期初账户信息","设置遗漏", JOptionPane.ERROR_MESSAGE);
     }
    private void missJigou(){
    	 JOptionPane.showMessageDialog(null, "未设置期初机构信息","设置遗漏", JOptionPane.ERROR_MESSAGE);
    }
    private void missCheliang(){
    	 JOptionPane.showMessageDialog(null, "未设置期初车辆信息","设置遗漏", JOptionPane.ERROR_MESSAGE);
    }
   private void missRenyuan(){
   	 JOptionPane.showMessageDialog(null, "未设置期初人员信息","设置遗漏", JOptionPane.ERROR_MESSAGE);
   }
   private void missKucun(){
	   	 JOptionPane.showMessageDialog(null, "未设置期初库存信息","设置遗漏", JOptionPane.ERROR_MESSAGE);
	   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Init.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
					new Init().setVisible(true);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accout;
    private javax.swing.JButton cheliang;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jigou;
    private javax.swing.JButton kucun;
    private javax.swing.JButton renyuan;
    // End of variables declaration//GEN-END:variables
}
